### ISSUE TITLE
RFM - Steam

### ISSUE THREAD

**Issue by brianmego** [chocolatey/chocolatey-package-requests#189]
Do not do enough Windows development to justify being the main maintainer of this package any longer. 

Source for the existing package exists here: https://github.com/brianmego/Chocolatey

**Comment by pauby** [comment]
I will pick this up.

**Comment by pauby** [comment]
Package complete and setup for automatic. Nothing to change in the package itself so it will nto be pushed until there is a new version.

**Comment by mikecole** [comment]
Hey @pauby, just an FYI, I already had steam running in AU using the same method you are to determine the version. The problem is that the version of the setup exe never increments. It appears they rely on using the same setup that has update built in. You may want to keep your eye on this. Let me know if you have any questions!

https://github.com/mikecole/chocolatey-packages/blob/master/automatic/steam/update.ps1

I'll remove my package so we don't clash.

**Comment by mikecole** [comment]
I'm 100% fine with you taking this over. Yours seems a bit more elegant than mine.

My approach with this package, since it was more difficult than others, was to just let the baked in updater in steam be the update solution. If you have alternative ideas, more power to you and feel free to bounce ideas off of me.

**Comment by pauby** [comment]
No, I agree with you. If they are not updating the version number then the package will never update the way it stands at the moment.

My thoughts off the top of my head are compare the hash of the new file with the hash stored in the chocolateyInstall.ps1 and if it's different then they have released a new installer and bump the third segment of the package up by 1 so it's a new version to Chocolatey.

If we leave the package to never update then the hash will become out of date anyway when a new version is released and downloaded with the package when it's installed. So we need to do something to keep the hash up to date at least.

I haven't looked at your package at all (don't have time just now sadly but may do so later) but please don't reject your package from Chocolatey (if that's what you were talking of doing). I will need to reject mine just now because of the version numbers. I will resubmit later. But let me know your thoughts re: the above.

**Comment by mikecole** [comment]
Comparing the hashes is a good idea.

However, my assumption is that it's not just the version on the setup that doesn't get incremented... I don't believe the setup is updated at all. So, if you compare the hashes I think it will always be the same. The problem with the package was never the hashes being wrong... it was that it never updated the software.

**Comment by pauby** [comment]
Ah. 

When I open the SteamSetup.exe yesterday with 7Zip the steam.exe and uninstall.exe had dates of July / August 2016 so I assumed that was the last time it was updated. 

I can see your package was submitted last November. So they likely do update the installer, just not very often.

To complicate matters the steam.exe has a version of 3.49.64.60 :)

It's a pity we can't get a hold of the old SteamSetup.exe installer and we could see what versions are on there.

**Comment by mikecole** [comment]
"I can see your package was submitted last November. So they likely do update the installer, just not very often." => The submission last November appears to have been when I first added it to AU. So, maybe it does, maybe it doesn't. :-) I honestly don't remember at this point.

**Comment by AdmiringWorm** [comment]
I'll first just re-iterate what I told @pauby yesterday.
The package IMO should be updated to be current with the latest recommendation.

To name a few things,
- Updating all the metadata that can be updated.
- Updating the install script to remove unneeded parameters (in this case removing the `unzipLocation` since it isn't used).
- Update the uninstall script to change out/remove
    - Use an alternative to `Get-WmiObject` (there is a built-in function to do what you are using it for [Get-OSArchitectureWidth][]
    - Remove the usage of `Write-ChocolateySuccess` and `Write-ChocolateyFailures`
    - Change detection of the uninstall to a registry based detection instead of hard coded paths, to get those paths you can use [Get-UninstallRegistryKey][]

it is recommended to run `choco new` on the latest chocolatey version to update the uninstall script.

With that said, regarding the steam setup rarely being updated:
There isn't really much that can be done in that regard, especially considering the user needs to be configured to actually update the application. So just keep it as it is right now IMO.

Regarding who should keep the package in their AU repo, that's something you two will need to decide for yourself though.

[Get-OSArchitectureWidth]: https://chocolatey.org/docs/helpers-get-o-s-architecture-width
[Get-UninstallRegistryKey]:  https://chocolatey.org/docs/helpers-get-uninstall-registry-key

**Comment by pauby** [comment]
"I'll first just re-iterate what I told @pauby yesterday.
The package IMO should be updated to be current with the latest recommendation.

To name a few things,"

That's why I suggested grabbing the 'elegant' bits.

But what I was looking for a second opinion on was how, assuming the installer version number is not updated, we increment the Chocolatey package version number. Segment etc. See above.

**Comment by AdmiringWorm** [comment]
I see, sorry missed that.

What is recommended from my perspective is to still use the 4th part of the version, but instead of using it originally as is, add a zero and a 1.
So for instance, the version: `2.10.91.91` becomes `2.10.91.9101`  (which seems to be what is already done).
But the important thing to remember is that all versions until `2.10.92` needs to have the 4th part higher then the previous package.
In this case, for instance the version `2.10.91.92` would need to be changed to `2.10.91.9200`.

**Comment by pauby** [comment]
@mikecole Do you want to keep this package or do you want me to re-submit mine? My intention would be to move this over to the core packages in the future (as I'm going to be looking at doing with all of my packages).

**Comment by mikecole** [comment]
Go ahead and re-submit yours, especially if you have a goal to move it to
the core packages.

**Comment by pauby** [comment]
Submitted now.

**Comment by AdmiringWorm** [comment]
The updated package have been approved
