### ISSUE TITLE
RFM ImageGlass

### ISSUE THREAD

**Issue by d2phap** [chocolatey/chocolatey-package-requests#234]
Current version is 4.0, the last package is 4.5
https://chocolatey.org/packages/imageglass

SHA-1 checksums is provided on download page,
Direct links to each version can be found on its [github](https://github.com/d2phap/ImageGlass).

**Comment by kkzinger** [comment]
Hi,

I have contacted dtgm (current Maintainer) and offered him help with maintaining this package. I dont use Ketarin for automated package building and therefor was not able to send him a pull request for his package repo.

I already built a automated package because I needed it at my local mirror. 
https://github.com/kkzinger/chocolatey-packages-new/tree/master/automatic/imageglass

Feel free to add me as maintainer if we dont hear from dtgm. I will report here when I get a response from him.

**Comment by kkzinger** [comment]
Have not heard of dtgm. Please add me as Maintainer of the package.

**Comment by AdmiringWorm** [comment]
@kkzinger please send out an email to the site admins, and we can get you added as a maintainer of the package.

**Comment by kkzinger** [comment]
Package submitted and awaiting moderation.

**Comment by kkzinger** [comment]
Package was approved.
