### ISSUE TITLE
RFP - Franz

### ISSUE THREAD

**Issue by SZanlongo** [chocolatey/chocolatey-package-requests#246]
Franz is your messaging app for WhatsApp, Facebook Messenger, Slack, HipChat, Telegram and many many more.

https://meetfranz.com/

**Comment by AdmiringWorm** [comment]
@SZanlongo I take it that this is the package you're looking for?
https://chocolatey.org/packages/franz

Since it doesn't have a stable release, it won't show up in normal searches unless you change the dropdown box to `Include Prereleases` on the package search page.

![image](https://user-images.githubusercontent.com/1474648/34786184-ac19dd44-f633-11e7-92a6-b3c73131dd20.png)

**Comment by SZanlongo** [comment]
That must be it, I was doing a regular search ad nothing showed up.

**Comment by AdmiringWorm** [comment]
closing this request then, as it already exist.
