### ISSUE TITLE
RFM saxonhe

### ISSUE THREAD

**Issue by Alegrowin** [chocolatey/chocolatey-package-requests#270]
We currently use saxonHE 9.8.0.1 that enable the xsltv3 transforms.

I tried to contact the package admin but without answer. I am ready to take over and publish a new version of the package.

**Comment by AdmiringWorm** [comment]
Since you wishes to take over as a new maintainer, then please send a message to the site admins (using the link on the left side when you are viewing the package details page.)

Then we can get you added as a maintainer, and get the ball rolling.

*NOTE: I'm guessing that by package admins you actually mean package maintainer.*

**Comment by Alegrowin** [comment]
Exact I meaned  package maintainer. :) I sent a request through the website. Thank you!

**Comment by AdmiringWorm** [comment]
Let us keep this request open until a new version have been pushed to chocolatey.

**Comment by Alegrowin** [comment]
https://chocolatey.org/packages/SaxonHE/9.8.0.11
