### ISSUE TITLE
RFP - LibreOffice Suite

### ISSUE THREAD

**Issue by Chronoshift111** [chocolatey/chocolatey-package-requests#283]
I am requesting a package to be made.
Application website:
https://www.libreoffice.org/

**Comment by Thilas** [comment]
It already exists: https://chocolatey.org/packages/libreoffice-fresh

**Comment by dimqua** [comment]
Also: https://chocolatey.org/packages/libreoffice-still

**Comment by Chronoshift111** [comment]
Dear Thomas D,

      Thank you for letting me know. I was unsure if there were any 
differences between the LibreOffice Fresh and the LibreOffice Suite.

Sincerely,

Chronoshift

**Comment by AdmiringWorm** [comment]
@Chronoshift111 there isn't any difference.

The LibreOffice Fresh/Still is both the LibreOffice Suite itself.

The Fresh edition being the edition where all the latest features are enabled, with the Still version taking a little safer approach with mainly adding stability/bug fixes, and only updating to new features when they have been sufficiently tested by users of LibreOffice Fresh.

*NOTE: That's my understanding at least*

Since this request is already covered by existing packages I will be closing this package request now.
