### ISSUE TITLE
RFP - Kdenlive

### ISSUE THREAD

**Issue by jeremyj563** [chocolatey/chocolatey-package-requests#355]
https://kdenlive.org/en/download/

Kdenlive is an acronym for KDE Non-Linear Video Editor. It is currently being ported to Windows as a GSOC project.

Now, you don’t need to do anything more to set up [on Windows]. To run Kdenlive, you just have to unzip the downloaded Kdenlive version, and start Kdenlive from kdenlive.exe in kdenlive-windows folder.

Current Windows beta download: https://files.kde.org/kdenlive/release/Kdenlive-18.04.1d-w64.zip

**Comment by nathanielwarner** [comment]
I've got a package almost ready to publish [here](https://github.com/nathanielwarner/kdenlive-chocolatey). There's a few (tracked) issues that I'd love some help with, but it's mostly working.

**Comment by luzpaz** [comment]
@nathanielwarner can you specify what the issues are ?

**Comment by jeremyj563** [comment]
> @nathanielwarner can you specify what the issues are ?

He said that the issues are tracked and he posted a link to the repository.

**Comment by nathanielwarner** [comment]
Hey guys, I'm in the process of updating the package and trying to resolve the issues (as @jeremyj563 said they are tracked on the repo) will get back to you soon.

**Comment by nathanielwarner** [comment]
It's working at this point, but when you uninstall it, you have to interact with the bundled uninstaller. I've been able to fix this by creating an uninstall script that invokes the uninstaller with '/S'. It uninstalls silently and correctly, but then chocolatey pops up a bunch of errors since it's still trying to run the auto uninstaller, which isn't possible because the software has been uninstalled. As far as chocolatey knows, the software is still installed.

Correct me if I'm wrong but it doesn't seem like there's currently a way to disable the auto uninstaller, so the best option is probably to just use the auto uninstaller and accept that some user interaction is required...

**Comment by nathanielwarner** [comment]
Thanks for the help @pauby, I think it's all set now. Still waiting on the confirmation email from chocolatey so I can get an API key and push to the repo...

**Comment by nathanielwarner** [comment]
So I still haven't received the confirmation email from chocolatey... I tried resending it to no avail. I'm not sure what to do next.

**Comment by luzpaz** [comment]
@pauby :point_up:

**Comment by pauby** [comment]
@nathanielwarner Have you reached out via the 'Contact Site Admins' link?

**Comment by nathanielwarner** [comment]
Alright, the email verification finally worked, and the package is uploaded and currently pending review.

**Comment by nathanielwarner** [comment]
Review passed today, and the package is up!
