### ISSUE TITLE
RFP - Oracle SQL Developer

### ISSUE THREAD

**Issue by PacMo66** [chocolatey/chocolatey-package-requests#383]
Database Development tool
common in enterprise enviroment
used every day by my team

> Oracle SQL Developer is a free and fully supported graphical tool for database development. With SQL Developer, you can browse database objects, run SQL statements and SQL scripts, and edit and debug PL/SQL statements. You can also run any number of provided reports, as well as create and save your own. SQL Developer enhances productivity and simplifies your database development tasks.

latest available via http://www.oracle.com/technetwork/developer-tools/sql-developer/downloads/index.html

**Comment by gsmitheidw** [comment]
Tempted to bite but this one will be trick to do because download requires clicking boxes for licence and then logging in. Hosting the package within the nupkg would be possible technically but it's Oracle, so legally that would want to be very clearly defined and agreed in writing.

**Comment by AdmiringWorm** [comment]
Well, since the license doesn't explicitly allow distribution of the installer, it certainly can't be embedded without permission from Oracle.

If there is a requirement to click the accept license boxes, this certainly complicates things. But maybe it could be worked around similiar in how it's done with the [jre](https://chocolatey.org/packages/jre8) and [jdk](https://chocolatey.org/packages/jdk8) packages.

Anyhow, I'll also mark this with an `Blocked Upstream` label, at least until we know for sure.

**Comment by qqgg231** [comment]
"requirement to click the accept license boxes" 
this is doable or bypassable

But in next step we need some account credentials

Is it okay to put these dummy account credentials into nupkg?

**Comment by gsmitheidw** [comment]
I think Oracle may dislike that, if they start seeing floods of downloads from one account they may block it or even worse, they might call the legal department to send cease and desist letters. They might even put a captcha to weed out scripts. 

I think it would be more successful if the nupkg could pass parameters for specific oracle credentials added per user and submit them through the site.

**Comment by JonasDralle** [comment]
[This StackExchange](https://stackoverflow.com/a/10959815) describes a way to download JDK without sign-ip:
```
curl -L -C - -b "oraclelicense=accept-securebackup-cookie" -O http://download.oracle.com/otn-pub/java/jdk/11.0.1+13/90cf5d8f270a4347a95050320eef3fb7/jdk-11.0.1_linux-x64_bin.tar.gz
```
maybe it's applicable for this package too?

**Comment by pauby** [comment]
Can we progress this package and remove the 'Blocked Upstream' label given the [comment](https://github.com/chocolatey/chocolatey-package-requests/issues/383#issuecomment-458087128) by @JonasDralle ?

**Comment by AdmiringWorm** [comment]
@pauby yeah, we probably can do that

**Comment by wcarson** [comment]
I'm new to chocolatey but would be interested in taking a shot at this one. I've played around with this a little bit, and it seems doable using a technique similar to what @JonasDralle proposed to get around having to click the license agreement. The issue is that at some point you have to have a (free) Oracle account to download the file. Is it acceptable to prompt for credentials during a chocolatey install (Get-Credential or similar) and/or allow the credentials to be passed in as argument to the install?

**Comment by pauby** [comment]
@wcarson the install should be silent. If it is absolutely required you could make sure the details are passed as package parameters.

**Comment by AdmiringWorm** [comment]
> the install should be silent.

Or at least unattended (silent would mean nothing is shown during install)

**Comment by pauby** [comment]
Unattended is a better description :)

**Comment by wcarson** [comment]
Just pushed an initial version of this package to the queue to be reviewed. To handle the Oracle Account requirement, it requires `--params "'/Username:{username} /Password:{password}'"` package params be specified. I've attached the initial version if anyone's feeling brave. (I have tested it locally on Win10 and on the [Chocolatey Texting Environment](https://github.com/chocolatey/chocolatey-test-environment) VM.)

[oracle-sql-developer.18.4.0.nupkg.zip](https://github.com/chocolatey/chocolatey-package-requests/files/2917247/oracle-sql-developer.18.4.0.nupkg.zip)

**Comment by wcarson** [comment]
Hi. I pushed an initial version for review. To handle the Oracle Account requirement, the package requires that the credentials be specified as package params: `"'/Username:{username} /Password:{password}'"`. The package is attached if anyone is feeling brave. (It's been tested locally on Win10 and on the [Chocolatey Testing Environment](https://github.com/chocolatey/chocolatey-test-environment) VM)

[oracle-sql-developer.18.4.0.nupkg.zip](https://github.com/chocolatey/chocolatey-package-requests/files/2917289/oracle-sql-developer.18.4.0.nupkg.zip)

**Comment by jpluimers** [comment]
For Oracle SQL Developer 19.1.0, I made a commit in a fresh branch at https://github.com/jpluimers/chocolatey-packages/commit/796b1e4978631daea42d7490fe5602346c482929

Two questions:

- What's the easiest way to test if I did not goof up that commit?
- Should I make a pull request to https://github.com/wcarson/chocolatey-packages in order to get it at https://chocolatey.org/packages or is there another way?

I am not sure for how long I will be using Oracle SQL Developer, but it is likely not for years, so I might not be able to provide updates for future Oracle SQL Developer versions.

**Comment by pauby** [comment]
> What's the easiest way to test if I did not goof up that commit?

Run the package through the [Chocolatey Test Environment](https://github.com/chocolatey/chocolatey-test-environment). However I noted your comments about it - the Vagrant environment is simply a bare, unpatched (for a reason) Windows Server 2012 R2 server. So if you can spin one of those up you can test your package on there. Ordinarily we woudl recommend not testing on your machine as you may not be able to pick up all the dependencies required. However as this is a change to an existing package, as long as you are mindful of it, you should be able to get away with testing it there.

> Should I make a pull request to wcarson/chocolatey-packages in order to get it at chocolatey.org/packages/oracle-sql-developer or is there another way?

If you're confident the code / package works then contacting the maintainer and submitting the PR would be a good way to start. This is the reason why we ask maintainers to provide a <packageSourceUrl> in their `.nuspec` file as it allows this process to happen.

You might want to reach out to [Gitter](https://gitter.im/chocolatey/choco) if you need more help.

**Comment by JonasDralle** [comment]
Hidden dependency: Internet Explorer needs to be initialized

> The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
<sub>[log](https://gist.github.com/JonasDralle/a39595592f9465c4964dda8a97e1bd1c)</sub>

Can be solved by opening IE and clicking a few boxes.

The far more pressing issue is that the package does not work on 64 Bit machines:

> ERROR: This package does not support 64 bit architecture.
<sub>[log](https://gist.github.com/JonasDralle/fe2fcdb6406a45c44c9ac4f5411ceb6b)</sub>

The log contains credentials which can be used by anyone for testing purposes:
USER `oracle.HdZks0KSKr@you-spam.com`
PASS `FZEOAO8ytZEMsrgDgK4s+4M0xADoy8y`
