### ISSUE TITLE
RFP - Baka MPlayer

### ISSUE THREAD

**Issue by dimqua** [chocolatey/chocolatey-package-requests#84]
Baka MPlayer is a free and open source, cross-platform, libmpv based multimedia player. Its simple design reflects the idea for an uncluttered and enjoyable environment for watching tv shows.

Downloads: https://github.com/u8sand/Baka-MPlayer/releases/latest

**Comment by chantisnake** [comment]
if you are familiar with PowerShell, I recommend you to try my github2choco module https://github.com/chantisnake/github2choco

I recommend you to use the latest version of github2choco and PSGitHub from the github repo, because the one on the gallery is somewhat outdated.

This package is not well documented, if you have any question about this package feel free to open an issue there.

**Comment by dimqua** [comment]
Abandoned project.
